#!/bin/bash

#########################################################
#                                                       #
#       ResilienceLab Tools - All rights reeserved      #
#       This tool allows to refresh outdated IPs        #
#       on GoDaddy DNS records.                         #       
#       Please refer to our github to learn more        #
#                                                       #       
#########################################################

#default variables

apikey=""
apisecret=""
domain="example.com"
arecord=""

#endpoint_getcurrentA="https://api.godaddy.com/v1/domains/$domain/records/A/$arecord"
#endpoint_setnewA="https://api.godaddy.com/v1/domains/$domain/records/A/$arecord"
#endpoint_getcurrentIP="https://ipinfo.io/json"

ip_regex="\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
headers_godaddy="Authorization: sso-key $apikey:$apisecret"

#read config -> default path to config
. /etc/resiliencetools/dynDNS.conf

#get current A record value
res=$(curl -s -X GET -H "$headers_godaddy" $endpoint_getcurrentA)
curr_aval="$(echo $res | grep -oE $ip_regex)"
#echo $res

#query ipinfo.io to get current public ip
raw=$(curl -s GET $endpoint_getcurrentIP)
curr_ipval="$(echo $raw | grep -oE $ip_regex| tr -s " " ".")"

#update your record if outdated
if [ $curr_aval != $curr_ipval ];then
        echo "A Record out of date"
        req_body='[{"data":"'$curr_ipval'","ttl":3600}]'
        echo $req_body
	nresult=$(curl -i -s -X PUT \
                -H "$headers_godaddy" \
                -H "Content-Type: application/json" \
                -d "$req_body" "$endpoint_setnewA")
	echo $nresult
fi


